### PR TITLE
Max/fix subscribe bugs

### LINKED ISSUE #472: Site Subscribe UI Bug
Subscription text doesn't change when subscribe button is clicked. Also, when returning to site after subscribing, if you haven't refreshed manually, it'll still have the old text.

Example:
Go to site - text says "Subscribe to site"
click button - Icon changes, but text still stays same
leave site
go back to site - Text says "subscribe to site" and icon is reset to old value

### PR DESCRIPTION
**Pull request by maxwolffe**
Fix #472

### CODE REVIEW

File: watershed-android/watershed/app/src/main/java/com/blueprint/watershed/Sites/SiteFragment.java [hunk 1]
```diff
@@ -189,7 +193,7 @@ public void onClick(View v) {
         subscribeButton.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View v) {
-                if (mSite.getSubscribed()) subscribeToSite();
```
Comment (nishdesai) [inline watershed-android/watershed/app/src/main/java/com/blueprint/watershed/Sites/SiteFragment.java]: haha this seems like a bug

**Comment by nishdesai** [comment]
If I'm reading this correctly, it seems like this should fix the multiple subscription bug, since the button changes to unsubscribe immediately. But I think we should still try to add validation for that on the backend @charlesx2013
